//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ChiTietGioHangs = new HashSet<ChiTietGioHang>();
        }
    
        public int maSanPham { get; set; }
        //[RegularExpression("^[a-zA-Z0-9 ]+$", ErrorMessage = "Tên sản phẩm không được nhập ký tự đăc biệt")]
        //[Required(ErrorMessage ="Tên sản phẩm không được để trống")]
        public string tenSanPham { get; set; }
        public string moTa { get; set; }
        public string hinhAnh { get; set; }
        public bool kichHoat { get; set; }
        //[Required(ErrorMessage ="Gián bán không được để trống")]
        public double giaBan { get; set; }
        public Nullable<double> giaKhuyenMai { get; set; }
        public Nullable<int> maHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
    }
}
